version: '3.3'

services:
  auth:
    image: bitnami/oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    environment:
      - OAUTH2_PROXY_CLIENT_ID="${CLIENT_ID}"
  app:
    image: jonathangilroypowell/basic-aspnet-webapp:latest
    environment: 
      - ASPNETCORE_URLS="http://+:8080"
